function [Dates , Data] = readTimeSeriesTable(filename)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   TIMESERIES19COVIDCONFIRMED = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   TIMESERIES19COVIDCONFIRMED = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   timeseries19covidConfirmed = importfile('time_series_19-covid-Confirmed.csv', 2, 461);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/03/19 08:14:06

%% Initialize variables.
delimiter = ',';
startRow = 1;
startCol = 4;

%% Format string for each line of text:
formatSpec = '%q';

%% Open the text file.
fileID = fopen(filename,'r');

%%
frewind(fileID)
tline = fgetl(fileID);
M = textscan(tline,formatSpec, 'Delimiter', delimiter);

%% Close the text file.
fclose(fileID);

%% read table text file.
data1 = csvread(filename,startRow,startCol );
data2 = csvread(filename,startRow,startCol+1 );

%% Post processing 
Dates = M{1, 1}(5:end);
date_cnt = length(Dates);
Data = [data1(1:209,1:date_cnt); data2(209:end,1:date_cnt);];
